### ISSUE TITLE
New Chinese Financial aid project profile on ODM

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_profile_pages#135]
@acorbi @Huyeng 
![image](https://cloud.githubusercontent.com/assets/14996905/24460400/801afb50-149e-11e7-965f-914d293f7b9e.png)

I think there still needs to be adjustments made or I'm doing something wrong - The filter isn't work even though I've inputted data into the backend. 

There is no Map ID field in my table so not sure why it's generated that on the front end?

**Comment by acorbi** [comment]
I can check it if you provide me with the necessary info:

>  the filters I set don't seem to be working
Which columns do you want filters for?

> There is no Map ID field in my table so not sure why it's generated that on the front end?
Will check this

> Also the AIDDATA project ID needs to be hyperlinked which it is but doesn't look hyperlinked.
There is an option for that, I'll do it

**Comment by acorbi** [comment]
So I have set the following config so there is a filter by sector and the rows are grouped by sector:

![screenshot from 2017-03-29 17-22-29](https://cloud.githubusercontent.com/assets/384894/24462492/63341f7a-14a4-11e7-9a8f-b1ca44b449ff.png)

good news: the filter appears and is functional
bad news: rows are not being grouped. @Huyeng can you please check it?

**Comment by prustar** [comment]
Thanks for the update. I made some changes to test out the 'index' and added the total calculations. Unfortunately it cuts off one of the calculations : 

![image](https://cloud.githubusercontent.com/assets/14996905/24465693/3c043386-14ae-11e7-93f4-1a843fba420f.png)

The last field "pipeline/identification" should say 33.

**Comment by Huyeng** [comment]
> bad news: rows are not being grouped. @Huyeng can you please check it?
It works on ODC site, let me check why ODM doesn't work.

> The last field "pipeline/identification" should say 33.
The number of "pipeline/identification" is not displayed because the the texts is not marched (Match case is requested). Thus, the texts that add into the "Show Total Numbers of Columns, separated by line breaks (English)" field are requited exactly the same case format that available on the table.
For example, on the spreadsheet, "Pipeline/identification", the "identification" is lower case, so if you add the "Pipeline/Identification" like the title sentence, it won't show.

**Comment by Huyeng** [comment]
After checking, the group row function is working properly, the problem is styling issue on ODM site only, for other counties is fine. 

The issue is logged on: https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/820
