### ISSUE TITLE
Error link of the Related profile page on ODC website

### ISSUE THREAD

**Issue by vatana92** [OpenDevelopmentMekong/wp-odm_profile_pages#182]
Hi @acorbi and Bong @Huyeng, there is an issue regarding the "Related profiles" on ODC's profile pages including: [Natural protected areas](https://opendevelopmentcambodia.net/profiles/natural-protected-areas/), [Fisheries conservation areas](https://opendevelopmentcambodia.net/profiles/fisheries-conservation-areas/), [Community forestry](https://opendevelopmentcambodia.net/profiles/community-forestry/), [Hydropower dams](https://opendevelopmentcambodia.net/profiles/hydropower-dams/), [Mining licenses](https://opendevelopmentcambodia.net/profiles/mining-licenses/). When you click on the hyperlink profiles under the "Related profiles"of those 5 profiles mentioned above, it will bring you to ODMekong page with the URL of WorPress signup (https://opendevelopmentmekong.net/wp-signup.php?new=cambodia) as you can see in the attached screenshot. 

![image](https://user-images.githubusercontent.com/19201022/36407113-786cfd94-162e-11e8-9082-9bbf49dfd966.png)

![image](https://user-images.githubusercontent.com/19201022/36407235-6bee1368-162f-11e8-879b-1777e308dad5.png)

**Comment by Huyeng** [comment]
@vatana92, this issue is not related to coding issue, but they are the old urls of ODC that have not updated. To fix it, please go to edit page of the profile, but find Related Profile Pages (English) and Related Profile Pages (Khmer), then update the urls. 

![screenshot_52](https://user-images.githubusercontent.com/6613530/36407509-b4ce4114-1631-11e8-8dc8-bbab7ff448ad.png)

![screenshot_53](https://user-images.githubusercontent.com/6613530/36407508-b49d4a32-1631-11e8-9b1c-27b7ead816ac.png)

**Comment by vatana92** [comment]
Thank Bong @Huyeng! All pages are fixed.
