### ISSUE TITLE
Notice: Undefined index: bio_name in profile page

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_profile_pages#82]
Notice: Undefined index: name 
The field name has value, but it is not shown, Not found is shown instead.
![screenshot_1](https://cloud.githubusercontent.com/assets/6613530/20427885/b79ae9ac-adb8-11e6-886c-85486cf5a0fc.jpg)

![screenshot_2](https://cloud.githubusercontent.com/assets/6613530/20427884/b76f0990-adb8-11e6-9b1d-aa89bf3804a9.jpg)

**Comment by Huyeng** [comment]
The field  bio_name has value when print_r() function is called, but in table, still not found. 
This happened in PP site, and also Production site. Any idea on that, @acorbi ?
![screenshot_3](https://cloud.githubusercontent.com/assets/6613530/20461686/fecb14de-af37-11e6-9667-d9e0899a59af.jpg)


URL: https://pp.opendevelopmentcambodia.net/profiles/prey-lang-landscape/prey-lang-biodiversity-database
https://opendevelopmentcambodia.net/profiles/prey-lang-landscape/prey-lang-biodiversity-database

**Comment by Huyeng** [comment]
This is the notified error: 
![screenshot_4](https://cloud.githubusercontent.com/assets/6613530/20461725/0eeb9a4a-af39-11e6-9afe-7da12b84ceb4.jpg)

**Comment by acorbi** [comment]
Hey @Huyeng any progress on this Issue? I understand is not fixed yet. I'll try to fix it in the next hours

**Comment by acorbi** [comment]
@Huyeng I found the root of this Issue. Strangely, the string **bio_name** (which I renamed to english_name just for testing) specified on the CSV file had a **ZERO WIDTH SPACE** character on it. which was causing the code to think that *$profiles[$key]* was returning empty string because in reality it was doing *$profile['bio_name<200B>']*.

This one was very difficult to identify since even Atom does not show this character. It was when I pasted the string on my terminal when I could see it.

Anyway, I have fixed the issue by removing ZERO WIDTH SPACE character on the **parse_mapping_pairs** function on **wp-odm_theme**, which is the function responsible for parsing the values specified on the profile's editing screen. See https://github.com/OpenDevelopmentMekong/wp-odm_theme/pull/612

**Comment by Huyeng** [comment]
That's thing should be noted. Thanks.

**Comment by Huyeng** [comment]
@acorbi, actually, the Zero Width space contains in the attribute setting of the profile page, not the csv file. 
We tried to rename the field name before as well, but it is not solved. However, when check the attribute setting, the zero space is found. Cheers!
